# Site settings
site: Muhammad Ali
title: Muhammad Ali Suyunov - Shaxsiy Blog
keywords: muhammadali, blog, portfolio, suyunov
description: >-
  Muhammad Ali Suyunovning shaxsiy blogi va portfolioli sayti.
lang: uz
timezone:  Asia/Tashkent
# repo: https://github.com/muhammadalisuyunov07-cmd/muhammadalisuyunov07-cmd.github.io
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
# discus-identifier:  XXX

# Author settings
author:
  name: Muhammad Ali Suyunov
  bio: Veb ishlab chiquvchi. Yangi texnologiyalarni o'rganishni yaxshi ko'raman.
  picture: assets/images/profile.png 
  github: muhammadalisuyunov07-cmd # github username
  # twitter: username # twitter username
  # facebook: username # facebook username
  # instagram: username # instagram username
  # youtube: url # youtube username
  # linkedin: username # linkedin username
  # email: email@example.com # email address


# URL settings
url: "https://muhammadalisuyunov07-cmd.github.io/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false